baseURL: "https://samuele-cozzi-io.github.io/website/"
title: "Samuele Cozzi"
paginate: 10
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-4ZEPW1ZG79

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Samuele Cozzi"
    description: "The Samuele Cozzi Blog"
    keywords: [Blog, Portfolio, PaperMod]
    #author: Me
    #images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    disableShare: true
    disableHLJS: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://samuele-cozzi-io.github.io/website/imgs/logo/logo.ico"
        favicon16x16: "https://samuele-cozzi-io.github.io/website/imgs/logo/16x16.png"
        favicon32x32: "https://samuele-cozzi-io.github.io/website/imgs/logo/32x32.png"
        apple_touch_icon: "https://samuele-cozzi-io.github.io/website/imgs/logo/AppIcon86x86@2x.png"
        safari_pinned_tab: "https://samuele-cozzi-io.github.io/website/imgs/logo/AppIcon40x40@2x.png"

    label:
        text: "Samuele Cozzi Blog"
        icon: "https://samuele-cozzi-io.github.io/website/imgs/logo/AppIcon40x40@2x.png"
        iconHeight: 40

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Samuele Cozzi"
        subtitle: ""
        imageUrl: "https://samuele-cozzi-io.github.io/website/imgs/avatar.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        # buttons:
        #     - name: Posts
        #       url: posts
        #     - name: Tags
        #       url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/samuele-cozzi-02650119"
        - name: github
          url: "https://github.com/samuele-cozzi"
        #- name: medium
        #  url: "https://twitter.com/samu_tech"

    analytics:
        google:
            SiteVerificationTag: "G-4ZEPW1ZG79"
        # bing:
        #     SiteVerificationTag: "XYZabc"
        # yandex:
        #     SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: true

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 1
        - identifier: search
          name: search
          url: /search/
          weight: 2
        - identifier: archives
          name: archives
          url: /archives/
          weight: 5
        # - identifier: categories
        #   name: categories
        #   url: /categories/
        #   weight: 10
        # - identifier: tags
        #   name: tags
        #   url: /tags/
        #   weight: 20

defaultContentLanguage: en
languages:
  en:
    title: My blog
    weight: 1

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary